# Generated by Django 2.2.13 on 2020-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewsql', '0003_auto_20190908_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpacksizeunit',
            name='material_pack_name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='materialpacksizeunit',
            name='material_pack_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L'), ('EA', '个/瓶/张/托')], max_length=100, null=True, verbose_name='包装单位'),
        ),
    ]
