# Generated by Django 2.2.13 on 2020-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewsql', '0006_auto_20200816_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
    ]
