# Generated by Django 2.2.13 on 2020-08-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewsql', '0008_auto_20200818_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
